openapi: "3.0.0"
info:
  version: 1.0.0
  title: Cart
  license:
    name: MIT
paths:
  /delivery/order/{orderId}:
    get:
      operationId: showUserOrders
      parameters:
        - name: orderId
          in: path
          required: true
          description: The id of usr
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Items"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /delivery/usr/{usrId}:
    get:
      operationId: findByUsrId
      parameters:
        - name: usrId
          in: path
          required: true
          description: The id of usr
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Item:
      type: object
      required:
        - productId
        - quantity
      properties:
        productId:
          type: string
        quantity:
          type: integer
          format: int32

    Order:
      type: object
      properties:
        orderId:
          type: string
        usrId:
          type: string
        content:
          type: array
          items:
            $ref: "#/components/schemas/Item"


    Items:
      type: array
      items:
        $ref: "#/components/schemas/Item"
    ItemFields:
      title: item field
      type: object
      description: field for cart CRUD.
      allOf:
        - $ref: '#/components/schemas/Item'
        - type: object
          properties:
            cart:
              title: Current Cart
              type: array
              items:
                $ref: "#/components/schemas/Item"
      required:
        - productId
        - quantity
        - cart
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
